name: Deploy to Firebase Hosting on PR

on: pull_request

permissions:
  checks: write
  contents: read
  pull-requests: write

jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Set up Node.js (use the correct version for your project)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Make sure the Node.js version matches your project

      # Install dependencies, including devDependencies like Vite
      - name: Install dependencies
        run: npm install

      # Build the app (ensure Vite is used here)
      - name: Build the app
        run: npm run build

      # Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CONTACT_MANAGEMENT_SYSTE_9F674 }}
          projectId: contact-management-syste-9f674
